# Generated by Django 2.2.18 on 2022-12-08 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('descr', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Product Category',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('img', models.ImageField(blank=True, upload_to='products_images')),
                ('descr', models.TextField(blank=True)),
                ('short_descr', models.CharField(blank=True, max_length=64)),
                ('pr', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quant', models.PositiveIntegerField(default=0)),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.KorCategory')),
            ],
        ),
    ]
